# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: dev
  displayName: Development
  jobs:
    - job: deploy
      displayName: Build and Deploy Static Web App
      steps:
        - checkout: self
          submodules: true
        - task: NodeTool@0
          inputs:
            versionSpec: "14.x"
          displayName: "Install Node.js"
        - bash: |
            echo "Listing PreBuild..."
            ls -la
            echo "Listing PreBuild Complete!"
        - script: |
            npm install -g webpack webpack-cli --save-dev
            npm install
            npx webpack --progress --config webpack.dev.config.ts
            npx webpack --progress --config webpack.prod.config.ts
            npm run test
          displayName: "npm install, run webpack"
        - bash: |
            echo "Listing PostBuild..."
            ls -la
            echo "Listing PostBuild Complete!"
        - task: AzureStaticWebApp@0
          inputs:
            app_location: 'dist'
            skip_app_build: true
            azure_static_web_apps_api_token: $(deployment_token_dev)

- stage: stg
  displayName: Staging
  dependsOn: dev
  jobs:
    - job: waitForValidation
      displayName: Wait for external validation    
      timeoutInMinutes: 4320
      pool: server
      steps:   
       - task: ManualValidation@0
         timeoutInMinutes: 1440
         inputs:
          notifyUsers: |
            chesda@2020spaces.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'reject'
    - job: deploy
      displayName: Deploy Static Web App
      dependsOn: waitForValidation
      steps:
        - checkout: self
          submodules: true
        - task: NodeTool@0
          inputs:
            versionSpec: "14.x"
          displayName: "Install Node.js"
        - bash: |
            echo "Listing PreBuild..."
            ls -la
            echo "Listing PreBuild Complete!"
        - script: |
            npm install -g webpack webpack-cli --save-dev
            npm install
            npx webpack --progress --config webpack.dev.config.ts
            npx webpack --progress --config webpack.prod.config.ts
            npm run test
          displayName: "npm install, run webpack"
        - bash: |
            echo "Listing PostBuild..."
            ls -la
            echo "Listing PostBuild Complete!"
        - task: AzureStaticWebApp@0
          inputs:
            app_location: 'dist'
            skip_app_build: true
            azure_static_web_apps_api_token: $(deployment_token_stg)

- stage: prod
  displayName: Production
  dependsOn: stg
  jobs:
    - job: waitForValidation
      displayName: Wait for external validation    
      timeoutInMinutes: 8640
      pool: server
      steps:   
       - task: ManualValidation@0
         timeoutInMinutes: 4320
         inputs:
          notifyUsers: |
            chesda@2020spaces.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'reject'
    - job: deploy
      displayName: Build and Deploy Static Web App
      dependsOn: waitForValidation
      steps:
        - checkout: self
          submodules: true
        - task: NodeTool@0
          inputs:
            versionSpec: "14.x"
          displayName: "Install Node.js"
        - bash: |
            echo "Listing PreBuild..."
            ls -la
            echo "Listing PreBuild Complete!"
        - script: |
            npm install -g webpack webpack-cli --save-dev
            npm install
            npx webpack --progress --config webpack.dev.config.ts
            npx webpack --progress --config webpack.prod.config.ts
            npm run test
          displayName: "npm install, run webpack"
        - bash: |
            echo "Listing PostBuild..."
            ls -la
            echo "Listing PostBuild Complete!"
        - task: AzureStaticWebApp@0
          inputs:
            app_location: 'dist'
            skip_app_build: true
            azure_static_web_apps_api_token: $(deployment_token_prod)